FTVPI-2156: Fix for Crash  java.lang.NoClassDefFoundError: android.provider.Settings
[Problem]
Settings.Global is only available from API 17 onwards.

[Root Cause]
The change for supporting Dolby over optical out in FTV Edition
caused regression in devices running API Level 16 and below.

[Solution]
Add check for API Level. Also did some more cleanup and improvements
in code.

Change-Id: I04a0a80274798cf2c19258f8cc27ea2d07311a87
Reviewed-on: https://e-gerrit.labcollab.net/49697
Reviewed-by: Srikanth Peddibhotla <peddisri@lab126.com>
Tested-by: Srikanth Peddibhotla <peddisri@lab126.com>
Reviewed-by: Tarun Solanki <tarunsol@lab126.com>